# /mnt: non-persistent data
# /datadrive: persistent data
# docker volumes are located in /mnt

services:
  snap_read:
    image: farcasterxyz/snapchain:latest
    pull_policy: always
    init: true
    environment:
      RUST_BACKTRACE: "full"
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        #!/bin/bash
        cat > config.toml <<EOF
        rpc_address="0.0.0.0:3383"
        http_address="0.0.0.0:3381"
        rocksdb_dir=".rocks"
        fc_network="Mainnet"
        read_node = true

        [statsd]
        prefix="snap_read"
        addr="0.0.0.0:8125"
        use_tags=false

        [gossip]
        address="/ip4/0.0.0.0/udp/3382/quic-v1"
        bootstrap_peers = "/ip4/54.236.164.51/udp/3382/quic-v1, /ip4/54.87.204.167/udp/3382/quic-v1, /ip4/44.197.255.20/udp/3382/quic-v1, /ip4/34.195.157.114/udp/3382/quic-v1, /ip4/107.20.169.236/udp/3382/quic-v1"

        [consensus]
        validator_addresses = ["6bc2d8901443de856d2670b0c2ea12b6727132fa830f9030d3a44ac5da9b1a72", "67474a42e0c6507198b73373b0558dfc94616b976ecfdf5c45fae11e2bee7102", "81032ecefa4260e5a63424f5a4b8b18b52d717a52583b3ffe22c4a7b084911b8", "2c0f58a364b7959c85e49b5a50d14d220c16f8bd7879b0d5d3f68b32de83ecb8", "29696eb40eb900a329a8d2542edef15d552c9ba6ded7882276be1e9eca090970"]
        shard_ids = [1,2]
        num_shards = 2

        [snapshot]
        endpoint_url = "https://e1f9f185c6e63471dd39f96abd3413c4.r2.cloudflarestorage.com"
        load_db_from_snapshot=true
        EOF
        exec $0 $@ # Now run the original command
    command: [ "./snapchain", "--config-path", "config.toml" ]
    restart: always
    ports:
      - "3381:3381/tcp"
      - "3382:3382/udp"
      - "3383:3383/tcp"
    volumes:
      - /mnt/point/rocks:/app/.rocks
      - /mnt/point/rocks-snapshot:/app/.rocks.snapshot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3381/v1/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - snapchain

  # caddy:
  #   image: caddy:latest
  #   restart: unless-stopped
  #   environment:
  #     - WEB_HOST_URL
  #   ports:
  #     - '8080:80'       # HTTP
  #     - '8443:443'      # HTTPS
  #     - '8443:443/udp'  # HTTPS UDP
  #     - '5000:5000'     # Redash
  #     - '9000:9000'     # Replicator web UI
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - /mnt/point/caddy-data:/data
  #     - /mnt/point/caddy-config:/config
  #   networks:
  #     - snapchain

  shuttle:
    build:
      context: .
      dockerfile: Dockerfile.shuttle
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - HUB_HOST=snap_read:3383
      - HUB_SSL=false
      - POSTGRES_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - POSTGRES_SCHEMA=postgres
      - REDIS_URL=redis://redis:6379
      - COLORIZE=true
      - CONCURRENCY=4
      - SHARDS=0
      - SHARD_NUM=0
    volumes:
      - /mnt/point/shuttle-node_modules:/app/packages/shuttle/node_modules
    depends_on:
      snap_read:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - snapchain

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - /mnt/point/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - snapchain

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    command: --save "" --loglevel warning --maxmemory-policy noeviction
    volumes:
      - /mnt/point/redis-data:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: [ 'CMD-SHELL', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - snapchain

  redash:
    image: redash/redash:latest
    depends_on:
      - postgres
      - redis
    ports:
      - "5001:5000"
    environment:
      REDASH_DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres/${DB_NAME}"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
    volumes:
      - /mnt/point/redash-data:/app/data
    networks:
      - snapchain

  redash-worker:
    image: redash/redash:latest
    command: worker
    depends_on:
      - postgres
      - redis
    environment:
      REDASH_DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres/${DB_NAME}"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
    volumes:
      - /mnt/point/redash-data:/app/data
    networks:
      - snapchain

  redash-scheduler:
    image: redash/redash:latest
    command: scheduler
    depends_on:
      - postgres
      - redis
    environment:
      REDASH_DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres/${DB_NAME}"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
      REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
    volumes:
      - /mnt/point/redash-data:/app/data
    networks:
      - snapchain

  # snapchain_sync:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.snapchain_sync
  #   environment:
  #     - SNAPCHAIN_API=http://snap_read:3381
  #     - POSTGRES_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
  #     - MAX_WORKERS=10
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   restart: unless-stopped
  #   networks:
  #     - snapchain
  #   stdin_open: true
  #   tty: true

volumes:
  hubble-rocks:
  # caddy-data:
  # caddy-config:
  shuttle-node_modules:

networks:
  snapchain:
    driver: bridge 